language:
  - python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - pytest

after_script:
  - coveralls

after_success:
  - coveralls
  - codecov










