language:
  - python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverag

script:
  -pytest

after_script:
  -coveralls

before_install:

virtualenv:
  - system-site-packages: false








