language:
  - python

python:
  - "3.6"

env:
  - DB=postgres

install:
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP="run.py"
  - export 'flask migrate'
  - export FLASK_ENV="testing"
  - psql -c 'create database sendit_test;' -U postgres
  - export DB_URL='postgresql://postgres@localhost:5432/sendit_test'

script:
  - pytest --cov=app/

after_script:
  - coveralls

after_success:
  - codecov










