language:
  - python

python:
  - "3.6"

env:
  - DB=postgres
  - FLASK_ENV="development"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=app/

after_script:
  - coveralls

after_success:
  - codecov










